remote_theme: pmarsceill/just-the-docs

aux_links:
  "HMT web site":
    - "http://www.homermultitext.org/"
  "gh repo for documentation":
    - "https://github.com/homermultitext/documentation"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
